"""initial_schema

Revision ID: a3ba61a73b22
Revises: 
Create Date: 2026-03-05 21:30:22.433444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3ba61a73b22'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Primary key – auto-generated UUID.'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Plan name, e.g. Basic, Pro, Enterprise.'),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False, comment='Price per billing interval.'),
    sa.Column('interval', sa.String(length=20), nullable=False, comment="Billing cycle: 'monthly' or 'yearly'."),
    sa.Column('features', sa.JSON(), nullable=False, comment='JSON with feature flags and limits.'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Primary key – auto-generated UUID.'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Unique e-mail address used for login.'),
    sa.Column('full_name', sa.String(length=255), nullable=False, comment='Full display name of the user.'),
    sa.Column('avatar_url', sa.String(length=512), nullable=True, comment="Optional URL pointing to the user's profile picture."),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='Bcrypt-hashed password.'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Primary key – auto-generated UUID.'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Business display name.'),
    sa.Column('slug', sa.String(length=255), nullable=False, comment='URL-safe unique slug for the tenant.'),
    sa.Column('plan_id', sa.Uuid(), nullable=False, comment='FK → plans.id – subscription plan for this tenant.'),
    sa.Column('settings', sa.JSON(), nullable=False, comment='JSON with theme, logos, active_features, etc.'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether this tenant account is active.'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('invitations',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Primary key – auto-generated UUID.'),
    sa.Column('tenant_id', sa.Uuid(), nullable=False, comment='FK → tenants.id – tenant that sent the invitation.'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Invitee e-mail address.'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='Role to assign: owner, co_owner, admin, or staff.'),
    sa.Column('token', sa.String(length=255), nullable=False, comment='Unique token used in the invitation link.'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when this invitation expires.'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('memberships',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Primary key – auto-generated UUID.'),
    sa.Column('user_id', sa.Uuid(), nullable=False, comment='FK → users.id.'),
    sa.Column('tenant_id', sa.Uuid(), nullable=False, comment='FK → tenants.id.'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='Role: owner, co_owner, admin, or staff.'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Membership status: active or suspended.'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Primary key – auto-generated UUID.'),
    sa.Column('tenant_id', sa.Uuid(), nullable=False, comment='FK → tenants.id – owning tenant.'),
    sa.Column('user_id', sa.Uuid(), nullable=False, comment='FK → users.id – the customer who placed the order.'),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False, comment='Total amount for the order.'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Order status, e.g. pending, confirmed, completed, cancelled.'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the order was created.'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Primary key – auto-generated UUID.'),
    sa.Column('tenant_id', sa.Uuid(), nullable=False, comment='FK → tenants.id – owning tenant.'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Product display name.'),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False, comment='Unit price of the product.'),
    sa.Column('is_combo', sa.Boolean(), nullable=False, comment='True if this product is a combo (bundle).'),
    sa.Column('stock', sa.Integer(), nullable=False, comment='Available inventory count.'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Primary key – auto-generated UUID.'),
    sa.Column('tenant_id', sa.Uuid(), nullable=False, comment='FK → tenants.id – tenant offering the service.'),
    sa.Column('user_id', sa.Uuid(), nullable=False, comment='FK → users.id – the customer.'),
    sa.Column('staff_id', sa.Uuid(), nullable=False, comment='FK → memberships.id – assigned staff member.'),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False, comment='Date and time of the appointment.'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Appointment status: scheduled, completed, cancelled.'),
    sa.ForeignKeyConstraint(['staff_id'], ['memberships.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('combo_items',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Primary key – auto-generated UUID.'),
    sa.Column('parent_id', sa.Uuid(), nullable=False, comment='FK → products.id – the combo product.'),
    sa.Column('child_id', sa.Uuid(), nullable=False, comment='FK → products.id – the contained product.'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='Number of child product units in the combo.'),
    sa.ForeignKeyConstraint(['child_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('combo_items')
    op.drop_table('appointments')
    op.drop_table('products')
    op.drop_table('orders')
    op.drop_table('memberships')
    op.drop_table('invitations')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('plans')
    # ### end Alembic commands ###
